AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - example/**/*
    - gemfiles/vendor/**/*
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
