AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/NumericLiterals:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
