language: ruby
sudo: false
cache: bundler
bundler_args: "" # make version bump not break all tests
branches:
  only: master
before_install: gem install bundler
script: bundle exec rake spec
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
gemfile:
- gemfiles/rails50.gemfile
- gemfiles/rails51.gemfile
- gemfiles/rails52.gemfile
- gemfiles/rails60.gemfile
matrix:
  include:
    - rvm: 2.3 # lowest supported ruby
      script: bundle exec rubocop
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails60.gemfile
