language: ruby
sudo: false
cache: bundler
bundler_args: ""
branches:
  only: master
before_install: gem update --system
rvm:
  - 2.2.4
  - 2.3.3
  - 2.4.0
gemfile:
 - gemfiles/rails50.gemfile
 - gemfiles/rails51.gemfile
