language: ruby
sudo: false
cache: bundler
bundler_args: "" # make version bump not break all tests
branches:
  only: master
before_install: gem install bundler
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
 - gemfiles/rails50.gemfile
 - gemfiles/rails51.gemfile
 - gemfiles/rails52.gemfile
